countries = [
    {name: 'Andorra'},
    {name: 'United Arab Emirates'},
    {name: 'Afghanistan'},
    {name: 'Antigua and Barbuda'},
    {name: 'Anguilla'},
    {name: 'Albania'},
    {name: 'Armenia'},
    {name: 'Netherlands Antilles'},
    {name: 'Angola'},
    {name: 'Antarctica'},
    {name: 'Argentina'},
    {name: 'American Samoa'},
    {name: 'Austria'},
    {name: 'Australia'},
    {name: 'Aruba'},
    {name: 'Azerbaijan'},
    {name: 'Bosnia and Herzegovina'},
    {name: 'Barbados'},
    {name: 'Bangladesh'},
    {name: 'Belgium'},
    {name: 'Burkina Faso'},
    {name: 'Burundi'},
    {name: 'Benin'},
    {name: 'Bermuda'},
    {name: 'Brunei'},
    {name: 'Bolivia'},
    {name: 'Brazil'},
    {name: 'Bahamas'},
    {name: 'Bhutan'},
    {name: 'Bouvet Island'},
    {name: 'Botswana'},
    {name: 'Belarus'},
    {name: 'Belize'},
    {name: 'Canada'},
    {name: 'Cocos [Keeling] Islands'},
    {name: 'Congo [DRC]'},
    {name: 'Central African Republic'},
    {name: 'Congo [Republic]'},
    {name: 'Switzerland'},
    {name: "Côte d'Ivoire"},
    {name: 'Cook Islands'},
    {name: 'Chile'},
    {name: 'Cameroon'},
    {name: 'China'},
    {name: 'Colombia'},
    {name: 'Costa Rica'},
    {name: 'Cuba'},
    {name: 'Cape Verde'},
    {name: 'Christmas Island'},
    {name: 'Cyprus'},
    {name: 'Czech Republic'},
    {name: 'Germany'},
    {name: 'Djibouti'},
    {name: 'Denmark'},
    {name: 'Dominica'},
    {name: 'Dominican Republic'},
    {name: 'Ecuador'},
    {name: 'Estonia'},
    {name: 'Egypt'},
    {name: 'Western Sahara'},
    {name: 'Eritrea'},
    {name: 'Spain'},
    {name: 'Ethiopia'},
    {name: 'Finland'},
    {name: 'Fiji'},
    {name: 'Falkland Islands [Islas Malvinas]'},
    {name: 'Micronesia'},
    {name: 'Faroe Islands'},
    {name: 'France'},
    {name: 'Gabon'},
    {name: 'United Kingdom'},
    {name: 'Grenada'},
    {name: 'Georgia'},
    {name: 'French Guiana'},
    {name: 'Guernsey'},
    {name: 'Ghana'},
    {name: 'Gibraltar'},
    {name: 'Greenland'},
    {name: 'Gambia'},
    {name: 'Guinea'},
    {name: 'Guadeloupe'},
    {name: 'Equatorial Guinea'},
    {name: 'Greece'},
    {name: 'South Georgia and the South Sandwich Islands'},
    {name: 'Guatemala'},
    {name: 'Guam'},
    {name: 'Guinea-Bissau'},
    {name: 'Guyana'},
    {name: 'Gaza Strip'},
    {name: 'Hong Kong'},
    {name: 'Heard Island and McDonald Islands'},
    {name: 'Honduras'},
    {name: 'Croatia'},
    {name: 'Haiti'},
    {name: 'Hungary'},
    {name: 'Indonesia'},
    {name: 'Ireland'},
    {name: 'Israel'},
    {name: 'Isle of Man'},
    {name: 'India'},
    {name: 'British Indian Ocean Territory'},
    {name: 'Iraq'},
    {name: 'Iran'},
    {name: 'Iceland'},
    {name: 'Italy'},
    {name: 'Jersey'},
    {name: 'Jamaica'},
    {name: 'Jordan'},
    {name: 'Japan'},
    {name: 'Kenya'},
    {name: 'Kyrgyzstan'},
    {name: 'Cambodia'},
    {name: 'Kiribati'},
    {name: 'Comoros'},
    {name: 'Saint Kitts and Nevis'},
    {name: 'North Korea'},
    {name: 'South Korea'},
    {name: 'Kuwait'},
    {name: 'Cayman Islands'},
    {name: 'Kazakhstan'},
    {name: 'Laos'},
    {name: 'Lebanon'},
    {name: 'Saint Lucia'},
    {name: 'Liechtenstein'},
    {name: 'Sri Lanka'},
    {name: 'Liberia'},
    {name: 'Lesotho'},
    {name: 'Lithuania'},
    {name: 'Luxembourg'},
    {name: 'Latvia'},
    {name: 'Libya'},
    {name: 'Morocco'},
    {name: 'Monaco'},
    {name: 'Moldova'},
    {name: 'Montenegro'},
    {name: 'Madagascar'},
    {name: 'Marshall Islands'},
    {name: 'Macedonia [FYROM]'},
    {name: 'Mali'},
    {name: 'Myanmar [Burma]'},
    {name: 'Mongolia'},
    {name: 'Macau'},
    {name: 'Northern Mariana Islands'},
    {name: 'Martinique'},
    {name: 'Mauritania'},
    {name: 'Montserrat'},
    {name: 'Malta'},
    {name: 'Mauritius'},
    {name: 'Maldives'},
    {name: 'Malawi'},
    {name: 'Mexico'},
    {name: 'Malaysia'},
    {name: 'Mozambique'},
    {name: 'Namibia'},
    {name: 'New Caledonia'},
    {name: 'Niger'},
    {name: 'Norfolk Island'},
    {name: 'Nigeria'},
    {name: 'Nicaragua'},
    {name: 'Netherlands'},
    {name: 'Norway'},
    {name: 'Nepal'},
    {name: 'Nauru'},
    {name: 'Niue'},
    {name: 'New Zealand'},
    {name: 'Oman'},
    {name: 'Panama'},
    {name: 'Peru'},
    {name: 'French Polynesia'},
    {name: 'Papua New Guinea'},
    {name: 'Philippines'},
    {name: 'Pakistan'},
    {name: 'Poland'},
    {name: 'Saint Pierre and Miquelon'},
    {name: 'Pitcairn Islands'},
    {name: 'Puerto Rico'},
    {name: 'Palestinian Territories'},
    {name: 'Portugal'},
    {name: 'Palau'},
    {name: 'Paraguay'},
    {name: 'Qatar'},
    {name: 'Réunion'},
    {name: 'Romania'},
    {name: 'Serbia'},
    {name: 'Russia'},
    {name: 'Rwanda'},
    {name: 'Saudi Arabia'},
    {name: 'Solomon Islands'},
    {name: 'Seychelles'},
    {name: 'Sudan'},
    {name: 'Sweden'},
    {name: 'Singapore'},
    {name: 'Saint Helena'},
    {name: 'Slovenia'},
    {name: 'Svalbard and Jan Mayen'},
    {name: 'Slovakia'},
    {name: 'Sierra Leone'},
    {name: 'San Marino'},
    {name: 'Senegal'},
    {name: 'Somalia'},
    {name: 'Suriname'},
    {name: 'São Tomé and Príncipe'},
    {name: 'El Salvador'},
    {name: 'Swaziland'},
    {name: 'Turks and Caicos Islands'},
    {name: 'Chad'},
    {name: 'French Southern Territories'},
    {name: 'Togo'},
    {name: 'Thailand'},
    {name: 'Tajikistan'},
    {name: 'Tokelau'},
    {name: 'Timor-Leste'},
    {name: 'Turkmenistan'},
    {name: 'Tunisia'},
    {name: 'Tonga'},
    {name: 'Turkey'},
    {name: 'Trinidad and Tobago'},
    {name: 'Tuvalu'},
    {name: 'Taiwan'},
    {name: 'Tanzania'},
    {name: 'Ukraine'},
    {name: 'Uganda'},
    {name: 'U.S. Minor Outlying Islands'},
    {name: 'United States'},
    {name: 'Uruguay'},
    {name: 'Uzbekistan'},
    {name: 'Vatican City'},
    {name: 'Saint Vincent and the Grenadines'},
    {name: 'Venezuela'},
    {name: 'British Virgin Islands'},
    {name: 'U.S. Virgin Islands'},
    {name: 'Vietnam'},
    {name: 'Vanuatu'},
    {name: 'Wallis and Futuna'},
    {name: 'Samoa'},
    {name: 'Kosovo'},
    {name: 'Yemen'},
    {name: 'Mayotte'},
    {name: 'South Africa'},
    {name: 'Zambia'},
    {name: 'Zimbabwe'}
]
organizations = [
    {name: 'Argentina'},
    {name: 'Australia'},
    {name: 'Austria'},
    {name: 'Azerbaijan'},
    {name: 'Flanders'},
    {name: 'Wallonia'},
    {name: 'Brazil'},
    {name: 'Bulgaria'},
    {name: 'Canada'},
    {name: 'Chile'},
    {name: 'China'},
    {name: 'Colombia'},
    {name: 'Czech Republic'},
    {name: 'Denmark'},
    {name: 'Ecuador'},
    {name: 'Estonia'},
    {name: 'Finland'},
    {name: 'France'},
    {name: 'Georgia'},
    {name: 'Germany'},
    {name: 'Ghana'},
    {name: 'Greece'},
    {name: 'Hungary'},
    {name: 'India'},
    {name: 'Indonesia'},
    {name: 'Italy'},
    {name: 'Japan'},
    {name: 'Kazakhstan'},
    {name: 'Korea'},
    {name: 'Latvia'},
    {name: 'Liberia'},
    {name: 'Lithuania'},
    {name: 'Mexico'},
    {name: 'Moldova'},
    {name: 'Mongolia'},
    {name: 'Netherlands'},
    {name: 'Norway'},
    {name: 'Paraguay'},
    {name: 'Philippines'},
    {name: 'Poland'},
    {name: 'Romania'},
    {name: 'Russia'},
    {name: 'Serbia'},
    {name: 'Slovakia'},
    {name: 'Spain'},
    {name: 'Sweden'},
    {name: 'Switzerland'},
    {name: 'Thailand'},
    {name: 'Turkey'},
    {name: 'Ukraine'},
    {name: 'Uruguay'},
    {name: 'USA'},
    {name: 'Venezuela'},
    {name: 'Vietnam'}
]
categories = [
    {name: 'Host family'},
    {name: 'YFU Students'},
    {name: 'Volunteers'},
    {name: 'Seminars and events'},
    {name: 'School'},
    {name: 'Travel'},
    {name: 'Alumni'}
]
keywords = [
    {word: 'fun'},
    {word: 'culture'},
    {word: 'architecture'},
    {word: 'food'},
    {word: 'monuments'}
]

users = [
    {email:'nielsswimberghe@gmail.com', password: 'nielsswimberghe@gmail.com',roles:[:reader]},
    {email:'nswimberghe@yfu-is.org', password: 'nswimberghe@yfu-is.org',roles:[:admin]},
    {email:'fwolf@yfu-is.org', password: 'fwolf@yfu-is.org',roles:[:admin]},
    {email:'jbeatty@yfu-is.org', password: 'jbeatty@yfu-is.org',roles:[:admin]},
    {email:'jhalbardier@yfu-is.org', password: 'jhalbardier@yfu-is.org',roles:[:admin]},
    {email:'abekte@yfu-is.org', password: 'abekte@yfu-is.org',roles:[:admin]},
    {email:'kastrom@yfu-is.org', password: 'kastrom@yfu-is.org',roles:[:admin]}
]

countries.each do |country|
    Country.find_or_create_by(name:country[:name],show_in_form:true)
end
organizations.each do |organization|
    YfuOrganization.find_or_create_by(name:organization[:name],show_in_form:true)
end
categories.each do |category|
    Category.find_or_create_by(name:category[:name])
end
keywords.each do |keyword|
    keyword_record = Keyword.find_or_create_by(word:keyword[:word])
    keyword_record[:is_predefined]=true
    keyword_record.save!
end
users.each do |user|
    user_record = User.find_by_email(user[:email])
    if user_record.nil?
        user_record = User.new
        user_record.email=user[:email]
        user_record.password=user[:password]
        user_record.password_confirmation=user[:password]
        user_record.roles << user[:roles]
        user_record.save!
    end
end